security:
  password_hashers:
    Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

  providers:
    app_user_provider:
      entity:
        class: App\Entity\Usuario
        property: username

  firewalls:
    api_login:
      pattern: ^/api/login
      stateless: true
      json_login:
        check_path: /api/login_check
        success_handler: lexik_jwt_authentication.handler.authentication_success
        failure_handler: lexik_jwt_authentication.handler.authentication_failure
    api:
      pattern: ^/api/
      stateless: true
      provider: app_user_provider
      jwt: ~

  # Control de acceso
  access_control:
    - path: ^/api/producto/all
      roles: [PUBLIC_ACCESS]
    - path: ^/api/pedido/new
      roles: [ROLE_CLIENTE, ROLE_ADMIN]
    - path: ^/api/producto/resenia/new
      roles: [ROLE_CLIENTE, ROLE_ADMIN]
    - path: ^/api/user/.*
      roles: [ROLE_CLIENTE, ROLE_ADMIN]
    - path: ^/api/user/admin/.*
      roles: [ ROLE_CLIENTE, ROLE_ADMIN ]
    - path: ^/api/pedido/usuario/all
      roles: [ROLE_CLIENTE, ROLE_ADMIN]

when@test:
  security:
    password_hashers:
      Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
        algorithm: auto
        cost: 4  # Valor más bajo posible para bcrypt
        time_cost: 3  # Valor más bajo posible para argon
        memory_cost: 10  # Valor más bajo posible para argon
